### ISSUE TITLE
Problema con caracteres especiales

### ISSUE THREAD

**Issue by Radigar** [duhow/Telegram-PHP#1]
Parece que existe algún tipo de problema con la codificación, cuando en la propiedad "text" se incluyen caracteres especiales. Por ejemplo hice una prueba con "Hola!" y el bot responde pero si en su lugar ponemos "¡Hola!" deja de responder para este caso. 

```
if($tg->text_command("start")){
  $tg->send
    ->text("¡Hola!")
  ->send();
}
```

**Comment by duhow** [comment]
Raro por eso. Parece que es problema tuyo. Puede que sea de la propia codificación de archivo (gestionalo en el propio editor de texto que utilices).

![image](https://cloud.githubusercontent.com/assets/1145001/22949306/1299beee-f302-11e6-9c2c-43167427ab56.png)

**Comment by Radigar** [comment]
Cierto era la codificación del archivo, ¡muchas gracias @duhow por la rápida contestación y por el proyecto!

**Comment by duhow** [comment]
Gracias a ti! Cualquier duda o sugerencia ya sabes dónde estoy ;)
