### ISSUE TITLE
button foreach

### ISSUE THREAD

**Issue by gillangit** [duhow/Telegram-PHP#14]
can you add array button function. 
example:

```php
foreach($info as $i){
->row->button($i->title, $i->subtitle)->end_row();
}
```

or

```php
$tg->send
	->text("title")
	->inline_keyboard()
		->row()
			->button(array(title=>subtitle,title2=>subtitle2)
		->end_row()
	->show()
	->send();
```

**Comment by duhow** [comment]
https://github.com/duhow/Telegram-PHP/blob/7a305874d45c0c46818d0954d3deaa411899e6e5/src/Keyboards/InlineKeyboard.php#L14

That is already done for both keyboards...
