### ISSUE TITLE
You May Want To Set $use_internal_resolver To FALSE By Default

### ISSUE THREAD

**Issue by taoteh1221** [duhow/Telegram-PHP#15]
I just tracked down a bug on my setup that uses your class. $use_internal_resolver should be set to FALSE here as the default (letting CURL resolve the domain ip via regular DNS), otherwise no connection can be established: https://github.com/duhow/Telegram-PHP/blob/master/src/Sender.php#L15

Other than that, it works great...thanks for such a minimal / effective class. :smile:

**Comment by duhow** [comment]
The intention of using internal resolver was to lower the amount of DNS queries.. this can also be done with hosts file, but as now Telegram uses a wide network range and they did not update all their servers, it started to cause problems when the certificate expired recently...

Thanks for the comment! :)

**Comment by taoteh1221** [comment]
Thanks for the info, was wondering why it was a feature. Thanks for the class, it works good.
