### ISSUE TITLE
is there any guide? I would like to generate private channel join link with time limit, how to do that, thanks.

### ISSUE THREAD

**Issue by HenrySWWong** [duhow/Telegram-PHP#16]
is there any guide? I would like to generate private channel join link with time limit, how to do that, thanks.

**Comment by duhow** [comment]
No guide, but for this repository / library it expects to receive POST content to process the Telegram message. Then just reply to message content by using Sender.php functions.

PRs with documentation and help are welcome :)

**Comment by HenrySWWong** [comment]
thank you duhow
