### ISSUE TITLE
Image + Inline Keyboard

### ISSUE THREAD

**Issue by duhow** [duhow/Telegram-PHP#7]
```php
$this->telegram->send
	->inline_keyboard()
		->row()
			->button($this->telegram->emoji(":times:") . " " . "back", "backme-0", "TEXT")
		->end_row()
	->show()
	->file('photo', "https://*******/ctemp/".$this->telegram->text().".jpg");
```
>Severity: **Notice**
>Message:  Array to string conversion

Image is not sent.

Should encode inline_keyboard as JSON string, see official PHP **Request** method.

**Comment by aliyazdanipak** [comment]
thank you for your attention, I solve it  by changing  telegram model(file function).
`$this->content['reply_markup']=json_encode($inlinekeyboard);`
I saved a lot of time by using your model.
gods bless you !
